FROM rocker/rstudio:3.6.1

RUN sudo apt-get update && apt-get install -y libxml2 pandoc libcairo2-dev libxml2-dev libmagick++-dev

ARG RPKG=/tmp/pkg

ADD src ${RPKG}

RUN R -e "install.packages('desc')" 

RUN R -e "install.packages(desc::desc_get_deps('${RPKG}/DESCRIPTION')[['package']])" \
    && R CMD INSTALL ${RPKG} \
    && rm -rf /tmp/*
